set xlabel 'Dage'
set ylabel 'Antal individer'
set title 'Stochastic SEIHRS Model - 100 Replicates (Input 1)'
set grid
set key outside top center
set key maxcols 5
set style line 1 lc rgb '#8000FF00' lt 1 lw 1
set style line 2 lc rgb '#80FFA500' lt 1 lw 1
set style line 3 lc rgb '#80FF0000' lt 1 lw 1
set style line 4 lc rgb '#80800080' lt 1 lw 1
set style line 5 lc rgb '#800000FF' lt 1 lw 1
plot 'stochastic_replicates.txt' index 0 using 1:2 with lines ls 1 title 'S (Input 1)', \
'stochastic_replicates.txt' index 0 using 1:3 with lines ls 2 title 'E (Input 1)', \
'stochastic_replicates.txt' index 0 using 1:4 with lines ls 3 title 'I (Input 1)', \
'stochastic_replicates.txt' index 0 using 1:5 with lines ls 4 title 'H (Input 1)', \
'stochastic_replicates.txt' index 0 using 1:6 with lines ls 5 title 'R (Input 1)', \
'stochastic_replicates.txt' index 0 using 1:7 with lines ls 1 title 'S (Input 2)', \
'stochastic_replicates.txt' index 0 using 1:8 with lines ls 2 title 'E (Input 2)', \
'stochastic_replicates.txt' index 0 using 1:9 with lines ls 3 title 'I (Input 2)', \
'stochastic_replicates.txt' index 0 using 1:10 with lines ls 4 title 'H (Input 2)', \
'stochastic_replicates.txt' index 0 using 1:11 with lines ls 5 title 'R (Input 2)', \
'stochastic_replicates.txt' index 1 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 1 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 1 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 1 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 1 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 1 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 1 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 1 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 1 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 1 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 2 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 2 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 2 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 2 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 2 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 2 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 2 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 2 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 2 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 2 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 3 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 3 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 3 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 3 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 3 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 3 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 3 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 3 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 3 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 3 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 4 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 4 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 4 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 4 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 4 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 4 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 4 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 4 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 4 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 4 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 5 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 5 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 5 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 5 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 5 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 5 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 5 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 5 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 5 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 5 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 6 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 6 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 6 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 6 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 6 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 6 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 6 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 6 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 6 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 6 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 7 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 7 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 7 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 7 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 7 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 7 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 7 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 7 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 7 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 7 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 8 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 8 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 8 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 8 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 8 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 8 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 8 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 8 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 8 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 8 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 9 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 9 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 9 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 9 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 9 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 9 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 9 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 9 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 9 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 9 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 10 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 10 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 10 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 10 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 10 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 10 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 10 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 10 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 10 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 10 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 11 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 11 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 11 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 11 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 11 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 11 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 11 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 11 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 11 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 11 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 12 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 12 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 12 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 12 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 12 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 12 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 12 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 12 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 12 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 12 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 13 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 13 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 13 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 13 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 13 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 13 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 13 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 13 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 13 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 13 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 14 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 14 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 14 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 14 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 14 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 14 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 14 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 14 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 14 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 14 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 15 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 15 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 15 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 15 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 15 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 15 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 15 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 15 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 15 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 15 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 16 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 16 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 16 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 16 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 16 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 16 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 16 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 16 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 16 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 16 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 17 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 17 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 17 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 17 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 17 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 17 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 17 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 17 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 17 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 17 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 18 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 18 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 18 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 18 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 18 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 18 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 18 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 18 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 18 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 18 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 19 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 19 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 19 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 19 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 19 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 19 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 19 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 19 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 19 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 19 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 20 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 20 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 20 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 20 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 20 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 20 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 20 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 20 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 20 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 20 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 21 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 21 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 21 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 21 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 21 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 21 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 21 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 21 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 21 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 21 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 22 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 22 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 22 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 22 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 22 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 22 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 22 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 22 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 22 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 22 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 23 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 23 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 23 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 23 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 23 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 23 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 23 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 23 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 23 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 23 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 24 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 24 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 24 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 24 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 24 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 24 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 24 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 24 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 24 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 24 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 25 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 25 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 25 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 25 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 25 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 25 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 25 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 25 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 25 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 25 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 26 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 26 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 26 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 26 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 26 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 26 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 26 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 26 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 26 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 26 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 27 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 27 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 27 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 27 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 27 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 27 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 27 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 27 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 27 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 27 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 28 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 28 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 28 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 28 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 28 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 28 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 28 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 28 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 28 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 28 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 29 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 29 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 29 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 29 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 29 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 29 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 29 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 29 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 29 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 29 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 30 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 30 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 30 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 30 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 30 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 30 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 30 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 30 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 30 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 30 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 31 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 31 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 31 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 31 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 31 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 31 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 31 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 31 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 31 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 31 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 32 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 32 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 32 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 32 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 32 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 32 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 32 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 32 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 32 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 32 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 33 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 33 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 33 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 33 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 33 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 33 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 33 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 33 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 33 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 33 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 34 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 34 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 34 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 34 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 34 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 34 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 34 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 34 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 34 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 34 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 35 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 35 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 35 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 35 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 35 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 35 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 35 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 35 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 35 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 35 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 36 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 36 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 36 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 36 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 36 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 36 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 36 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 36 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 36 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 36 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 37 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 37 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 37 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 37 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 37 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 37 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 37 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 37 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 37 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 37 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 38 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 38 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 38 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 38 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 38 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 38 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 38 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 38 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 38 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 38 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 39 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 39 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 39 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 39 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 39 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 39 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 39 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 39 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 39 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 39 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 40 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 40 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 40 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 40 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 40 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 40 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 40 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 40 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 40 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 40 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 41 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 41 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 41 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 41 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 41 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 41 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 41 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 41 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 41 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 41 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 42 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 42 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 42 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 42 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 42 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 42 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 42 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 42 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 42 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 42 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 43 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 43 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 43 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 43 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 43 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 43 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 43 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 43 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 43 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 43 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 44 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 44 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 44 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 44 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 44 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 44 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 44 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 44 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 44 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 44 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 45 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 45 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 45 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 45 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 45 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 45 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 45 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 45 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 45 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 45 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 46 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 46 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 46 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 46 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 46 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 46 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 46 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 46 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 46 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 46 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 47 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 47 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 47 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 47 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 47 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 47 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 47 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 47 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 47 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 47 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 48 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 48 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 48 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 48 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 48 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 48 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 48 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 48 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 48 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 48 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 49 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 49 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 49 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 49 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 49 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 49 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 49 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 49 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 49 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 49 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 50 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 50 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 50 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 50 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 50 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 50 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 50 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 50 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 50 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 50 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 51 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 51 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 51 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 51 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 51 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 51 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 51 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 51 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 51 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 51 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 52 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 52 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 52 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 52 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 52 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 52 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 52 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 52 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 52 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 52 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 53 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 53 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 53 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 53 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 53 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 53 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 53 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 53 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 53 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 53 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 54 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 54 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 54 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 54 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 54 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 54 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 54 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 54 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 54 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 54 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 55 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 55 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 55 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 55 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 55 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 55 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 55 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 55 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 55 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 55 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 56 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 56 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 56 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 56 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 56 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 56 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 56 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 56 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 56 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 56 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 57 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 57 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 57 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 57 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 57 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 57 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 57 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 57 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 57 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 57 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 58 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 58 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 58 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 58 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 58 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 58 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 58 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 58 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 58 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 58 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 59 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 59 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 59 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 59 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 59 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 59 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 59 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 59 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 59 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 59 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 60 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 60 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 60 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 60 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 60 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 60 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 60 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 60 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 60 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 60 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 61 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 61 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 61 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 61 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 61 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 61 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 61 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 61 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 61 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 61 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 62 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 62 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 62 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 62 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 62 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 62 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 62 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 62 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 62 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 62 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 63 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 63 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 63 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 63 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 63 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 63 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 63 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 63 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 63 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 63 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 64 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 64 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 64 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 64 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 64 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 64 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 64 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 64 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 64 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 64 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 65 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 65 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 65 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 65 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 65 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 65 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 65 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 65 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 65 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 65 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 66 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 66 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 66 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 66 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 66 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 66 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 66 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 66 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 66 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 66 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 67 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 67 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 67 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 67 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 67 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 67 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 67 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 67 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 67 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 67 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 68 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 68 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 68 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 68 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 68 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 68 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 68 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 68 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 68 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 68 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 69 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 69 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 69 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 69 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 69 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 69 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 69 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 69 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 69 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 69 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 70 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 70 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 70 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 70 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 70 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 70 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 70 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 70 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 70 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 70 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 71 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 71 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 71 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 71 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 71 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 71 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 71 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 71 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 71 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 71 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 72 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 72 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 72 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 72 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 72 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 72 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 72 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 72 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 72 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 72 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 73 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 73 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 73 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 73 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 73 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 73 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 73 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 73 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 73 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 73 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 74 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 74 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 74 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 74 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 74 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 74 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 74 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 74 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 74 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 74 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 75 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 75 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 75 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 75 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 75 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 75 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 75 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 75 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 75 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 75 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 76 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 76 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 76 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 76 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 76 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 76 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 76 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 76 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 76 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 76 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 77 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 77 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 77 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 77 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 77 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 77 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 77 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 77 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 77 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 77 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 78 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 78 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 78 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 78 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 78 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 78 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 78 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 78 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 78 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 78 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 79 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 79 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 79 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 79 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 79 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 79 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 79 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 79 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 79 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 79 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 80 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 80 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 80 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 80 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 80 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 80 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 80 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 80 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 80 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 80 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 81 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 81 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 81 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 81 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 81 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 81 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 81 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 81 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 81 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 81 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 82 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 82 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 82 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 82 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 82 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 82 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 82 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 82 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 82 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 82 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 83 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 83 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 83 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 83 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 83 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 83 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 83 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 83 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 83 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 83 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 84 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 84 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 84 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 84 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 84 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 84 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 84 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 84 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 84 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 84 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 85 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 85 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 85 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 85 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 85 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 85 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 85 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 85 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 85 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 85 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 86 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 86 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 86 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 86 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 86 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 86 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 86 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 86 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 86 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 86 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 87 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 87 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 87 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 87 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 87 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 87 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 87 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 87 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 87 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 87 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 88 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 88 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 88 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 88 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 88 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 88 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 88 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 88 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 88 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 88 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 89 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 89 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 89 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 89 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 89 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 89 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 89 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 89 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 89 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 89 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 90 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 90 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 90 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 90 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 90 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 90 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 90 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 90 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 90 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 90 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 91 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 91 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 91 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 91 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 91 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 91 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 91 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 91 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 91 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 91 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 92 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 92 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 92 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 92 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 92 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 92 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 92 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 92 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 92 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 92 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 93 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 93 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 93 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 93 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 93 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 93 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 93 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 93 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 93 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 93 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 94 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 94 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 94 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 94 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 94 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 94 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 94 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 94 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 94 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 94 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 95 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 95 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 95 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 95 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 95 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 95 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 95 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 95 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 95 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 95 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 96 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 96 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 96 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 96 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 96 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 96 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 96 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 96 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 96 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 96 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 97 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 97 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 97 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 97 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 97 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 97 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 97 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 97 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 97 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 97 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 98 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 98 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 98 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 98 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 98 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 98 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 98 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 98 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 98 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 98 using 1:11 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 99 using 1:2 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 99 using 1:3 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 99 using 1:4 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 99 using 1:5 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 99 using 1:6 with lines ls 5 notitle, \
'stochastic_replicates.txt' index 99 using 1:7 with lines ls 1 notitle, \
'stochastic_replicates.txt' index 99 using 1:8 with lines ls 2 notitle, \
'stochastic_replicates.txt' index 99 using 1:9 with lines ls 3 notitle, \
'stochastic_replicates.txt' index 99 using 1:10 with lines ls 4 notitle, \
'stochastic_replicates.txt' index 99 using 1:11 with lines ls 5 notitle
pause -1 'Tast enter for at lukke'
